[package]
name = "kube-example-cnat"
version = "0.1.0"
description = "Cloud Native at. Runs `command` at `schedule` by creating a Pod."
keywords = ["kubernetes", "k8s", "kube", "example"]
homepage = "https://github.com/kazk/cnat-rs"
repository = "https://github.com/kazk/cnat-rs"
readme = "README.md"
authors = ["kazk <kazk.dev@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "cnat"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
futures = "0.3.5"
futures-util = "0.3.5"
kube = { version = "0.43.0", default-features = true, features = ["derive"] }
kube-derive = "0.43.0"
kube-runtime = "0.43.0"
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1"
tokio = { version = "^0.2.24", features = ["macros", "rt-core"] }
log = "0.4.11"
simple_logger = { version = "1.11.0", default-features = false }

[profile.release]
lto = true
