apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ats.example.kazk.dev
spec:
  group: example.kazk.dev
  names:
    kind: At
    singular: at
    plural: ats
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                command:
                  type: array
                  items:
                    type: string
              required: [schedule, command]
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}
