name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registry:
    if: ${{ github.repository == 'kazk/cnat-rs' }}
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Prepare
        id: prepare
        run: |
          # Extract version from Cargo.toml by
          # - Find first `version`
          # - Get the version string (assuming the format `version = "x.x.x"`)
          # - Remove quotes
          VERSION=$(grep version Cargo.toml | head -n 1 | awk '{ print $3 }' | tr -d \")
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=sha::$SHORT_SHA"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # Personal Access Token with `write:packages`
          # https://docs.github.com/en/free-pro-team@latest/packages/guides/about-github-container-registry#about-scopes-and-permissions-for-github-container-registry
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          tags: |
            ghcr.io/kazk/cnat:latest,ghcr.io/kazk/cnat:${{ steps.prepare.outputs.sha }},ghcr.io/kazk/cnat:${{ steps.prepare.outputs.version }}
